name: Continuous Deployment Pipeline

on:
    push:
        branches:
            - "main"
        paths:
            - "backend/**"
            - ".github/workflows/deploy.yaml"

jobs:
    dockerhub:
        name: Publish Docker Image(s) to Dockerhub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Cache Docker layers for Maintos
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache-maintos-backend
                  key: ${{ runner.os }}-buildx-maintos-backend-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-maintos-backend-

            - name: Build & Push Maintos Backend
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/maintos-backend:latest
                  cache-from: type=local,src=/tmp/.buildx-cache-maintos-backend
                  cache-to: type=local,dest=/tmp/.buildx-cache-maintos-backend-new,mode=max

            - name: Move Maintos cache
              run: |
                  rm -rf /tmp/.buildx-cache-maintos-backend
                  mv /tmp/.buildx-cache-maintos-backend-new /tmp/.buildx-cache-maintos-backend

    push:
        name: Push Code Stage
        needs: dockerhub
        runs-on: ubuntu-latest

        steps:
            - name: Sync local repo with remote repo
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/backend/"
                      sudo git fetch origin
                      sudo git reset --hard origin/main

    pull:
        name: Pull Image Stage
        needs: push
        runs-on: ubuntu-latest

        steps:
            - name: Pull the latest images(s)
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/backend/"
                      sudo docker compose pull

    deploy:
        name: Deploy Stage
        needs: pull
        runs-on: ubuntu-latest

        steps:
            - name: Deploy the latest build(s)
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/backend/"
                      sudo docker compose down
                      sudo docker compose up -d